name: TikTok Scout

on:
  schedule:
    # Runs every 30 minutes (avoid rate limits)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  search-tiktok:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        playwright install-deps
    
    - name: Run TikTok Scout
      env:
        CALLMEBOT_PHONE: ${{ secrets.CALLMEBOT_PHONE }}
        CALLMEBOT_APIKEY: ${{ secrets.CALLMEBOT_APIKEY }}
        PORTFOLIO_URL: ${{ secrets.PORTFOLIO_URL }}
        KEYWORDS: ${{ secrets.KEYWORDS }}
      run: python tiktok_scout.py
      timeout-minutes: 10
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-logs
        path: |
          *.log
        retention-days: 7
