name: XScout Bot

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run XScout bot (single search)
      env:
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        CALLMEBOT_PHONE: ${{ secrets.CALLMEBOT_PHONE }}
        CALLMEBOT_APIKEY: ${{ secrets.CALLMEBOT_APIKEY }}
        AUTO_REPLY: ${{ secrets.AUTO_REPLY }}
        PORTFOLIO_URL: ${{ secrets.PORTFOLIO_URL }}
        KEYWORDS: ${{ secrets.KEYWORDS }}
      run: timeout 180 python xscout_single_run.py || true
      timeout-minutes: 4
